[package]
name = "dbr-sim"
version = "0.1.0"
authors = ["Zyansheep <zyansheep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["sim", "cli"]

[dependencies]
sim = { path = "sim" }
anyhow = "1.0.41"
iced = { git = "https://github.com/zyansheep/iced" }
iced_native = { git = "https://github.com/zyansheep/iced" }
iced_graphics = { git = "https://github.com/zyansheep/iced" }
#iced = { git = "https://github.com/hecrj/iced", branch = "feature/dynamic-linking", package="iced_dynamic" }
#iced_native = { git = "https://github.com/hecrj/iced", branch = "feature/dynamic-linking", package="iced_dynamic" }
#iced_graphics = { git = "https://github.com/hecrj/iced", branch = "feature/dynamic-linking", package="iced_dynamic" }
iced_aw = { git = "https://github.com/zyansheep/iced_aw", features = ["tabs"] }
env_logger = "0.8.4"
rand = "0.8.4"
nalgebra = "0.27.1"

[dev-dependencies]
iced = { git = "https://github.com/zyansheep/iced", features = ["dynamic"] }
