[workspace]
members = [
	"dither", # Cross-Platform Network Implementation of Dither API

	"sim",
	# "sim/cli",
	"sim/gui", # Gui simulation
	"sim/device", # Dither Client controlled by stdin and stdout by sim/gui
]

[patch.crates-io]
netsim-embed = { path = "vendor/netsim-embed" }