[package]
name = "dbr-sim"
version = "0.1.0"
authors = ["Zyansheep <zyansheep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"node", # Transporter-Agnostic Dither Implementation
	"sim", # Internet Simulation Module
	"cli" # CLI for Internet Sim Module, Includes Encryption
]

[dependencies]
sim = { path = "sim" }
anyhow = "1.0.42"
iced = { git = "https://github.com/zyansheep/iced", features = ["canvas"] }
#iced_native = { git = "https://github.com/zyansheep/iced" }
#iced_graphics = { git = "https://github.com/zyansheep/iced" }
#iced = { git = "https://github.com/hecrj/iced", branch = "feature/dynamic-linking", package="iced_dynamic" }
#iced_native = { git = "https://github.com/hecrj/iced", branch = "feature/dynamic-linking", package="iced_dynamic" }
#iced_graphics = { git = "https://github.com/hecrj/iced", branch = "feature/dynamic-linking", package="iced_dynamic" }
iced_aw = { git = "https://github.com/zyansheep/iced_aw", features = ["tabs"] }
env_logger = "0.8.4"
rand = "0.8.4"
nalgebra = "0.27.1"
derivative = "2.2.0"
slotmap = "1.0.5"
tokio = "1.8.1"
futures = "0.3.16"

[dev-dependencies]
iced = { git = "https://github.com/zyansheep/iced", features = ["dynamic"] }
