[workspace]
members = [
	"node", # Transporter-Agnostic Dither Implementation
	"core", # Cross-Platform Network Implementation of Dither API

	"sim",
	"sim/cli",
	"sim/gui",
	"sim/device",
]

[patch.crates-io]
netsim-embed = { path = "vendor/netsim-embed" }