[package]
name = "sim"
version = "0.1.0"
authors = ["Zyansheep <zyansheep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
plot = ["plotters"]

[dependencies]
node = { path = "../node" }

anyhow = "1.0.42"
bitflags = "1.2.1"
derivative = "2.2.0"
env_logger = "0.8.4"
fancy-regex = "0.6.0"
log = "0.4.14"
plotters = { git = "https://github.com/zyansheep/plotters", optional = true }
priority-queue = "1.1.1"
rand = { version = "0.8.4", features = ["small_rng"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
bincode = "1.3.3"



ta = "0.5.0"
thiserror = "1.0.26"
vpsearch = "2.0.1"
permutation_iterator = "0.1.2"
csv = "1.1.6"
itertools = "0.10.1"
tokio = { version = "1.8.1", features = ["full"] }
