[package]
name = "sim"
version = "0.1.0"
authors = ["Zyansheep <zyansheep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# plot = ["plotters"]

[dependencies]
node = { path = "../node" }

tokio = { version = "1.11.0", features = ["full"] }

anyhow = "1.0.43"
bitflags = "1.3.2"
derivative = "2.2.0"
fancy-regex = "0.7.1"
log = "0.4.14"
# plotters = { git = "https://github.com/zyansheep/plotters", optional = true }

rand = { version = "0.8.4", features = ["small_rng"] }

serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
bincode = "1.3.3"

ta = "0.5.0"
thiserror = "1.0.29"
vpsearch = "2.0.1"
permutation_iterator = "0.1.2"
csv = "1.1.6"
itertools = "0.10.1"
nalgebra = "0.29.0"
petgraph = "0.6.0"
netsim-embed = "0.5.2"
netsim = "0.2.5"
