[package]
name = "device"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libdither = { path = "../../core" }
ron = "0.6.5"
serde = { version = "1.0.130", features = ["derive"] }
