[package]
name = "gui"
version = "0.1.0"
authors = ["zyansheep <zyansheep@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
iced = { version = "0.3.0", features = ["canvas", "tokio" ] }
iced_futures = "0.3.0"

iced_aw = { git = "https://github.com/iced-rs/iced_aw", features = ["tabs"] }
env_logger = "0.9.0"
rand = "0.8.4"
nalgebra = "0.29.0"
derivative = "2.2.0"
slotmap = "1.0.5"
tokio = "1.8.1"
futures = "0.3.16"
serde = "1.0.127"
sim = { path = ".." }
log = "0.4.14"
tokio-stream = "0.1.7"
